### ISSUE TITLE
StackOverflowError when loading data on a POJO that contains a value of the same type (e.g. a child node)

### ISSUE THREAD

**Issue by Thunderforge** [hazendaz/javabean-tester#242]
If a POJO contains an instance of itself (as in the case of a node containing a child node), then trying to run a ` .loadData().checkEquals().test()` results in a `StackOverflowError`.

## Example Code

```java
package com.example;

import com.codebox.bean.JavaBeanTester;
import org.junit.jupiter.api.Test;

public class FooNodeTest {

    public class FooNode {

        private String id;

        private FooNode child;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public FooNode getChild() {
            return child;
        }

        public void setChild(FooNode child) {
            this.child = child;
        }
    }

    @Test
    public void isPojo() {
        JavaBeanTester.builder(FooNode.class)
                .loadData()
                .checkEquals()
                .test();
    }
}
```

## Exception

```
java.lang.StackOverflowError
	at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:134)
	at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:734)
	at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:720)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:692)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.codebox.instance.ClassInstance.newInstance(ClassInstance.java:62)
	at com.codebox.bean.JavaBeanTesterWorker.getterSetterTests(JavaBeanTesterWorker.java:207)
	at com.codebox.bean.ValueBuilder.buildValue(ValueBuilder.java:74)
	at com.codebox.bean.JavaBeanTesterWorker.buildValue(JavaBeanTesterWorker.java:391)
	at com.codebox.bean.JavaBeanTesterWorker.getterSetterTests(JavaBeanTesterWorker.java:204)
	at com.codebox.bean.ValueBuilder.buildValue(ValueBuilder.java:74)
	at com.codebox.bean.JavaBeanTesterWorker.buildValue(JavaBeanTesterWorker.java:391)
	at com.codebox.bean.JavaBeanTesterWorker.getterSetterTests(JavaBeanTesterWorker.java:204)
	at com.codebox.bean.ValueBuilder.buildValue(ValueBuilder.java:74)
        [etc]
```

**Comment by hazendaz** [comment]
More details on #29.

Currently the project tries to load data deeply, need to add a circuit breaker to not do so with same class under test as it will just result in this condition.

**Comment by hazendaz** [comment]
resolved on master.  test code in place to prevent this type of issue from occuring again.
